import './globals.css'
import { Inter } from 'next/font/google'
import NavBar from "./components/navBar"
import Main from "./components/main"

import Footer from './components/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <NavBar/>
      {/* <Main /> */}
      {children}

      {/* <Data /> */}
      <Footer />
      </body>
    </html>
  )
}
